### ISSUE TITLE
Segment not found on the cluster

### ISSUE THREAD

**Issue by LaPetiteSouris** [liftbridge-io/liftbridge#225]
I have set up a Liftbridge cluster at work in production environment . I have 4 Liftbridge nodes and 3 NATS nodes , all on Kubernetes. I have about 1000-2000 message per minute.

At some random time in the week, I notice that the clients all fail to subscribe to the topic. 

The topic has 1 partition, replication factor is 3. 

Here below are the logs of one of the Liftbridge node (others nodes do not show anything abnormal)

```bash
time="2020-07-06 12:25:10" level=debug msg="api: FetchMetadata [ta.cvm_trigger_client_score]"
time="2020-07-06 12:25:10" level=debug msg="api: Subscribe [stream=ta.cvm_trigger_client_score, partition=0, start=LATEST, offset=0, timestamp=0]"
time="2020-07-06 12:25:10" level=error msg="api: Failed to subscribe to partition [subject=ta.cvm_trigger_client_score, stream=ta.cvm_trigger_client_score, partition=0]: rpc error: code = Internal desc = Failed to create stream reader: segment not found"
time="2020-07-06 12:25:10" level=debug msg="api: FetchMetadata [ta.cvm_trigger_client_score]"
time="2020-07-06 12:25:10" level=debug msg="api: Subscribe [stream=ta.cvm_trigger_client_score, partition=0, start=LATEST, offset=0, timestamp=0]"
time="2020-07-06 12:25:10" level=error msg="api: Failed to subscribe to partition [subject=ta.cvm_trigger_client_score, stream=ta.cvm_trigger_client_score, partition=0]: rpc error: code = Internal desc = Failed to create stream reader: segment not found"
```

Here below are the configuration of the seed node

```yaml

listen: 0.0.0.0:9292
host: liftbridge-alpha-re.api-dev.data.apps.com
port: 30170
data.dir: /data/liftbridge/alpha

activity.stream.enabled: true

# Configure logging.
logging:
  level: debug
  raft: true

# Define NATS cluster to connect to.
nats.servers:
  - nats://nats:nats@nats-alpha.tapubsub-rec.svc.cluster.local:6222
  - nats://nats:nats@nats-beta.tapubsub-rec.svc.cluster.local:6222
  - nats://nats:nats@nats-gamma.tapubsub-rec.svc.cluster.local:6222

# Specify message stream settings.
streams:
  retention.max:
    age: 2h
  compact.enabled: false

# Specify cluster settings.
clustering:
  server.id: alpha
  namespace: "ta.pubsub"
  raft.bootstrap.seed: true
  replica.max.lag.time: 20s

```

Here below are the configuration of the 3 remaining nodes in the cluster

```yaml
listen: 0.0.0.0:9292
host: liftbridge-beta-re.api-dev.data.apps.com
port: 30171
data.dir: /data/liftbridge/beta

activity.stream.enabled: true

# Configure logging.
logging:
  level: debug
  raft: true

# Define NATS cluster to connect to.
nats.servers:
  - nats://nats:nats@nats-alpha.tapubsub-rec.svc.cluster.local:6222
  - nats://nats:nats@nats-beta.tapubsub-rec.svc.cluster.local:6222
  - nats://nats:nats@nats-gamma.tapubsub-rec.svc.cluster.local:6222

# Specify message stream settings.
streams:
  retention.max:
    age: 2h
  compact.enabled: false

# Specify cluster settings.
clustering:
  server.id: beta
  namespace: "ta.pubsub"
  raft.bootstrap.seed: false
  replica.max.lag.time: 20s

```

Any idea what did I do wrong ?

I am thinking because I have only one partition  but there are multiple publishers that publish the message to the same partition. Not sure if it can be the problem ?
