### ISSUE TITLE
K8s Installation

### ISSUE THREAD

**Issue by hyprnick** [liftbridge-io/liftbridge#291]
Hello, I'm having lots of trouble trying to get this installed in K8s cluster running on AWS EKS.  

I took the base Kustomize files and setup the data volume mount using a PVC.  The pods are stuck in a crash loop: 

```
time="2020-12-01 04:50:13" level=info msg="Shutting down..."
panic: failed to recover or persist metadata state: open /tmp/liftbridge/liftbridge-default/liftbridge: permission denied

goroutine 1 [running]:
main.main()
	/go/src/github.com/liftbridge-io/liftbridge/main.go:25 +0x1bc
```

I tried to use the image liftbridge/liftbridge-k8s and I get the following error instead: 

```
Running in liftbridge-2...
time="2020-12-01 04:59:37" level=info msg="Shutting down..."
panic: failed to recover or persist metadata state: open /data/liftbridge: permission denied

goroutine 1 [running]:
main.main()
	/workspace/main.go:25 +0x1bc

```

Is there something trivial that I am missing? Appreciate the help!  

Here is the statefulset:  

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: liftbridge
spec:
  serviceName: "liftbridge-headless"
  podManagementPolicy: "Parallel"
  replicas: 3
  selector:
    matchLabels:
      app: liftbridge
  template:
    metadata:
      labels:
        app: liftbridge
    spec:
      containers:
        - name: liftbridge
          image: liftbridge/liftbridge-k8s:v1.3.0
          ports:
            - name: grpc
              containerPort: 9292
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-service=proto.API", "-addr=:9292"]
            initialDelaySeconds: 5
          volumeMounts:
            - name: liftbridge-data
              mountPath: /data
            - mountPath: /etc/liftbridge.yaml
              name: liftbridge-config
              subPath: liftbridge.yaml
      volumes:
        - configMap:
            name: config
          name: liftbridge-config
  volumeClaimTemplates:
  - metadata:
      name: liftbridge-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

```

**Comment by LaPetiteSouris** [comment]
I am wondering if it is related to `liftbridge ` or something with the configuration of your K8s cluster. I may suggest:

- In any of the pod you have on your cluster, try to see if you can access the claimed volume or not ?

- Try to change lifbridge config file to point to another data folder. Refer [data.dir](https://liftbridge.io/docs/configuration.html) in the doc for that.

Would it help ?

**Comment by riaan53** [comment]
Ran into same problem. The issue is the volume is mounted as root and liftbridge app runs under another user group. See https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by justinrush** [comment]
> Ran into same problem. The issue is the volume is mounted as root and liftbridge app runs under another user group. See https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

I just modified the [helm chart's]() statefulset and included an init container to do this:
```yaml
      initContainers:
        - name: chmod
          image: busybox:latest
          command:
            - /bin/chown
            - -R
            - "1001:1001"
            - /data
          volumeMounts:
          - mountPath: /data
            name: liftbridge-data
```
