### ISSUE TITLE
raft: failed to make requestVote RPC: target="{Voter 10.66.1.1:9292 10.66.1.1:9292}" error="nats: timeout"

### ISSUE THREAD

**Issue by strahe** [liftbridge-io/liftbridge#306]
Hi, 

I found that server.id is random string by default:

![image](https://user-images.githubusercontent.com/7932644/102956692-8f8cda00-4513-11eb-8130-d16640036c84.png)

but why use server as the address to connect here?

https://github.com/liftbridge-io/liftbridge/blob/27994688a5448ce0389fc59b16090f1c18595a5a/server/raft.go#L222

If I don't specify server.id, it will always be timeout. Only when I set server.id to ip:port can the connection succeed.

Am I missing something?

**Comment by tylertreat** [comment]
This error should not generally happen, but it depends on how you are configuring the cluster topology. Are you setting a node as a seed to bootstrap the cluster (`raft.bootstrap.seed`) or are you explicitly configuring the cluster with `raft.bootstrap.peers`?

In either case, once the cluster is established, newly started nodes will automatically join the cluster. Cluster management is done via NATS, not direct TCP connections, so `server.id` does not need to be an IP address. It's just used to namespace NATS communication.

**Comment by strahe** [comment]
@tylertreat Hi, thanks for answering my question, I am now stuck in other dilemmas.

first:

```
listen: 0.0.0.0:9292
host: 10.66.1.1
port: 9292
data.dir: /streaming/liftbridge/data

logging:
  level: debug
  recovery: true
  raft: true

clustering:
  server.id: 10.66.1.1:9292
  min.insync.replicas: 1

streams:
  retention.max.age: 0
  segment.max.bytes: 536870912

nats.servers:
  - nats://10.66.1.1:4222
  - nats://10.66.1.2:4222
  - nats://10.66.1.3:4222

```
run:

![image](https://user-images.githubusercontent.com/7932644/103050424-3bdfc680-45cf-11eb-90b5-b31d83482d2a.png)


second：

```
listen: 0.0.0.0:9292
host: 10.66.1.2
port: 9292
data.dir: /streaming/liftbridge/data

logging:
  level: debug
  recovery: true
  raft: true

clustering:
  server.id: 10.66.1.2:9292
  min.insync.replicas: 1

streams:
  retention.max.age: 0
  segment.max.bytes: 536870912

nats.servers:
  - nats://10.66.1.1:4222
  - nats://10.66.1.2:4222
  - nats://10.66.1.3:4222
```

run： 

![image](https://user-images.githubusercontent.com/7932644/103050565-9711b900-45cf-11eb-9f04-6652ad71993e.png)

the same time node 1:

![image](https://user-images.githubusercontent.com/7932644/103050613-ae50a680-45cf-11eb-97e0-4259dd38608b.png)

The third is similar to the second.

I have deleted the data and repeated it many times, still the same, I can make sure that their network and ports are connected, and nats are available.
