### ISSUE TITLE
panic: runtime error: possibly on loosing leader

### ISSUE THREAD

**Issue by ekbfh** [liftbridge-io/liftbridge#322]
Hello!

I get this panic in usual situation

```
liftbridge[27672]: time="2021-01-25 09:41:30" level=error msg="Error sending replication request for partition [subject=dispose.DGT, stream=dispose.DGT, partition=0]: nats: timeout"
liftbridge[27672]: time="2021-01-25 09:41:31" level=error msg="Replica mevent04 for partition [subject=dispose.DGT, stream=dispose.DGT, partition=1] exceeded max lag time (last seen: 15.00035756s, last caught up: 15.00035756s), removing from ISR"
Jan 25 09:41:31 mevent03 liftbridge[27672]: liftbridge[27672]: panic: runtime error: invalid memory address or nil pointer dereference
liftbridge[27672]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc789b5]
liftbridge[27672]: goroutine 84 [running]:
liftbridge[27672]: github.com/liftbridge-io/liftbridge/server.(*raftNode).isLeader(...)
liftbridge[27672]: /home/circleci/project/server/raft.go:70
liftbridge[27672]: github.com/liftbridge-io/liftbridge/server.(*Server).IsLeader(0xc0000381e0, 0x0)
liftbridge[27672]: /home/circleci/project/server/server.go:245 +0x65
liftbridge[27672]: github.com/liftbridge-io/liftbridge/server.(*metadataAPI).ShrinkISR(0xc00035e310, 0x1015320, 0xc000032038, 0xc00048e420, 0xc000000002)
liftbridge[27672]: /home/circleci/project/server/metadata.go:501 +0x46
liftbridge[27672]: github.com/liftbridge-io/liftbridge/server.(*replicator).shrinkISR(0xc0003fe0c0)
liftbridge[27672]: /home/circleci/project/server/replicator.go:200 +0xe9
liftbridge[27672]: github.com/liftbridge-io/liftbridge/server.(*replicator).tick(0xc0003fe0c0, 0xc0003bc2a0)
liftbridge[27672]: /home/circleci/project/server/replicator.go:178 +0x4e6
 liftbridge[27672]: github.com/liftbridge-io/liftbridge/server.(*replicator).start.func1()
 liftbridge[27672]: /home/circleci/project/server/replicator.go:82 +0x33
 liftbridge[27672]: github.com/liftbridge-io/liftbridge/server.(*Server).startGoroutine.func1(0xc00000c040, 0xc0000381e0)
 liftbridge[27672]: /home/circleci/project/server/server.go:900 +0x27
 liftbridge[27672]: created by github.com/liftbridge-io/liftbridge/server.(*Server).startGoroutine
 liftbridge[27672]: /home/circleci/project/server/server.go:899 +0x9a
 systemd[1]: liftbridge.service: main process exited, code=exited, status=2/INVALIDARGUMENT
 systemd[1]: Unit liftbridge.service entered failed state.
```
Config:
```
clustering:
    min.insync.replicas: 2
    raft.bootstrap.peers:
    - mevent02
    - mevent03
    - mevent04
    replica.fetch.timeout: 7s
    server.id: mevent02
cursors:
    stream.auto.pause.time: 0
    stream.partitions: 1
data:
    dir: /var/lib/liftbridge
host: *.84
logging:
    level: debug
    raft: true
nats.servers:
- nats://*.84:4222
- nats://*.85:4222
- nats://*.86:4222
streams:
    compact.enabled: false
    retention.max:
        age: 24h
```
Unfortunately, don't have data files on this moment
