### ISSUE TITLE
Infinite loop when fetch cursor without messages on __cursor

### ISSUE THREAD

**Issue by aversant** [liftbridge-io/liftbridge#365]
Hello. 

When stream `__cursors`  has no message (removed by retention policy) - call `FetchCursor` wait infinitive time. Step for reproduce:

config 
```yaml
cursors:
    stream.auto.pause.time: 0
    stream.partitions: 1
streams:
    compact.enabled: false
    retention.max:
        age: 20m
    segment.max:
        age: 5m

```

1. Set default retention policy by time to `stream` config: `retention.max` - 20m, `segment.max` - 5m
2. Start `Liftbridge` - it create `__cursor` stream
3.  Call some `SetCursor`
4. Wait until messages clean by retention
5. Reboot liftbridge (for clean Cursor Cache)
6. Fetch Cursor 

**Workaround** - not set retention by `time`, only by size or message count. But this will consume file descriptors, because compact worked only **inactive** segments and large size `retention.byte` will result in more segment files.
